# Generated by Django 4.2.1 on 2023-06-07 13:18

from django.db import migrations, models
import workshop.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pet_photos/', validators=[workshop.photos.validators.validate_file_size]),
        ),
    ]
